
import React from 'react';
import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";
import { toast } from "react-toastify";

const DownloadMenuButton = () => {
  const handleDownload = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      toast.error('Please allow pop-ups to download the menu');
      return;
    }

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Subway Menu with Prices 2025</title>
          <style>
            body {
              font-family: Arial, sans-serif;
              line-height: 1.6;
              color: #333;
              max-width: 800px;
              margin: 0 auto;
              padding: 20px;
            }
            h1, h2 {
              color: #222;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              margin: 15px 0;
            }
            th, td {
              border: 1px solid #ddd;
              padding: 12px;
              text-align: left;
            }
            th {
              background-color: #f5f5f5;
            }
            .footer {
              margin-top: 40px;
              text-align: center;
              font-size: 12px;
              color: #666;
            }
            @media print {
              .no-print {
                display: none;
              }
            }
          </style>
        </head>
        <body>
          <div class="no-print" style="text-align: right; margin-bottom: 20px;">
            <button onclick="window.print()">Print Menu</button>
          </div>
          ${document.querySelector('.container-custom')?.innerHTML || ''}
          <div class="footer">
            <p>Generated by Subway Nutrition Calculator - subway-nutrition-calculator.com</p>
            <p>Menu prices and availability may vary by location.</p>
            <p>This tool is not affiliated with or endorsed by Subway® Restaurants.</p>
          </div>
        </body>
      </html>
    `);

    printWindow.document.close();
    toast.success('Print preview opened. Use browser print function to save or print');
  };

  return (
    <Button
      onClick={handleDownload}
      className="flex items-center gap-2 mb-8"
      variant="outline"
    >
      <Download className="h-4 w-4" />
      Download Menu
    </Button>
  );
};

export default DownloadMenuButton;
